name: Build FCOS Image (Hosted Runner Friendly)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y podman qemu-utils curl

    - name: Prepare Writable Directories
      run: |
        mkdir -p builds/latest/x86_64
        chmod -R 777 builds

    - name: Pull CoreOS Assembler Image
      run: podman pull quay.io/coreos-assembler/coreos-assembler:latest

    - name: Run FCOS Build (Unprivileged)
      env:
        COSA_NO_KVM: "1"
      run: |
        podman run --rm --userns=keep-id -v ${GITHUB_WORKSPACE}:/srv:z quay.io/coreos-assembler/coreos-assembler:latest init
        podman run --rm --userns=keep-id -v ${GITHUB_WORKSPACE}:/srv:z quay.io/coreos-assembler/coreos-assembler:latest fetch
        podman run --rm --userns=keep-id -v ${GITHUB_WORKSPACE}:/srv:z quay.io/coreos-assembler/coreos-assembler:latest build
        podman run --rm --userns=keep-id -v ${GITHUB_WORKSPACE}:/srv:z quay.io/coreos-assembler/coreos-assembler:latest buildextend-qemu

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: fcos-qcow2
        path: builds/latest/x86_64/fedora-coreos-*.qcow2

        